services:
  database:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./storage/database/data:/var/lib/postgresql/data
