server:
  port: 8080
logging:
  level:
    root: INFO
spring:
  application:
    name: spring-jooq-example
  datasource:
    hikari:
      auto-commit: false
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      data-source-properties:
        ApplicationName: ${spring.application.name}
        stringtype: unspecified
        reWriteBatchedInserts: true
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
